# Generated by Django 4.0.2 on 2022-08-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennv', models.CharField(max_length=800)),
                ('theloai', models.CharField(max_length=1200)),
                ('congnang', models.CharField(max_length=1500)),
            ],
        ),
    ]
