# Generated by Django 4.0.2 on 2022-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='giachoi2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tengoi', models.CharField(max_length=500)),
                ('congdung', models.CharField(max_length=400)),
                ('chuatri', models.CharField(max_length=300)),
            ],
        ),
    ]
