# Generated by Django 4.0.2 on 2022-03-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='giachoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tengoi', models.CharField(max_length=300)),
                ('chucnamg', models.CharField(max_length=400)),
                ('khanang', models.CharField(max_length=500)),
                ('chongchidinh', models.CharField(max_length=600)),
            ],
        ),
    ]
